

export interface AtcScheduleItem {
    atc: string;
    rate: number;
    description: string;
}

export const atcWE: AtcScheduleItem[] = [
    { atc: 'WI010', rate: 5, description: 'Professionals (Lawyers, CPAs, Engineers, etc.)- If gross income for the current year did not exceed P3M' },
    { atc: 'WI011', rate: 10, description: 'Professional (Lawyers, CPAs, Engineers, etc) - If gross Income is more than P3M or VAT Registered regardless of amount' },
    { atc: 'WI020', rate: 5, description: 'Professional entertainers, such as, but not limited to, actors and actresses, singers, lyricist, composers, emcees - If gross income for the current year did not exceed P3M' },
    { atc: 'WI021', rate: 10, description: 'Professional entertainers such as, but not limited to actors & actresses, singers, lyricists, composers, emcees - If gross Income is more than P3M or VAT Registered regardless of amount' },
    { atc: 'WI030', rate: 5, description: 'Professional athletes, including basketball players, pelotaris and jockeys - If gross income for the current year did not exceed P3M' },
    { atc: 'WI031', rate: 10, description: 'Professional athletes including basketball players, pelotaris and jockeys - If gross income is more than P3M of VAT Registered regardless of amount' },
    { atc: 'WI040', rate: 5, description: 'All directors and producers involved in movies, stage, radio, television and musical productions - If gross income for the current year did not exceed P3M' },
    { atc: 'WI041', rate: 10, description: 'All directors and producers involved in movies, stage, radio, television and musical productions - If gross income is more than P3M of VAT Registered regardless of amount' },
    { atc: 'WI050', rate: 5, description: 'Management and technical consultants - If gross income for the current year did not exceed P3M' },
    { atc: 'WI051', rate: 10, description: 'Management and technical consultants - If gross income is more than P3M of VAT Registered regardless of amount' },
    { atc: 'WI060', rate: 5, description: 'Business and bookkeeping agents and agencies - If gross income for the current year did not exceed P3M' },
    { atc: 'WI061', rate: 10, description: 'Business and bookkeeping agents and agencies - If gross income is more that P3M of VAT Registered regardless of amount' },
    { atc: 'WI070', rate: 5, description: 'Insurance agents and insurance adjusters - If gross income for the current year did not exceed P3M' },
    { atc: 'WI071', rate: 10, description: 'Insurance agents and insurance adjusters - If gross income is more than P3M of VAT Registered regardless of amount' },
    { atc: 'WI080', rate: 5, description: 'Other recipients of talent fees - If gross income for the current year did not exceed P3M' },
    { atc: 'WI081', rate: 10, description: 'Other recipients of talent fees - If gross income is more than P3M or VAT Registered regardless of amount' },
    { atc: 'WI090', rate: 5, description: 'Fees of directors who are not employees of the company - If gross income for the current year did not exceed P3M' },
    { atc: 'WI091', rate: 10, description: 'Fees of directors who are not employees of the company - If gross income is more than P3M of VAT Registered regardless of amount' },
    { atc: 'WI100', rate: 5, description: 'Rentals- real/personal properties, poles, satellites & transmission facilities, billboards - Individual' },
    { atc: 'WI110', rate: 5, description: 'Cinematographic film rentals - Individual' },
    { atc: 'WI120', rate: 2, description: 'Income payments to prime contractors/sub-contractors - Individual' },
    { atc: 'WI130', rate: 15, description: 'Income distribution to beneficiaries of estates and trusts' },
    { atc: 'WI139', rate: 5, description: 'Gross commission or service fees of custom, insurance, stock, real estate, immigration and commercial brokers & fees of agents of professional entertainers - If gross income for the current year did not exceed P3M' },
    { atc: 'WI140', rate: 10, description: 'Gross commission or service fees of custom, insurance, stock, real estate, immigration and commercial brokers & fees of agents of professional entertainers - If gross income is more than P3M or VAT Registered regardless of amount' },
    { atc: 'WI151', rate: 5, description: 'Payments for medical/dental/veterinary services thru Hospitals/ Clinics/Health Maintenance Organizations, including direct payments to service providers - If gross income for the current year did not exceed P3M' },
    { atc: 'WI150', rate: 10, description: 'Payments for medical/dental/veterinary services thru Hospitals/ Clinics/Health Maintenance Organizations, including direct payments to service providers - If gross income > P3M of VAT Registered regardless of amount' },
    { atc: 'WI152', rate: 10, description: 'Payment by the general professional partnerships (GPP) to its partners - If gross income for the current year did not exceed P720,000' },
    { atc: 'WI153', rate: 15, description: 'Payment by the General Professional Partnerships (GPPs) to its partners - If gross income exceeds P720,000' },
    { atc: 'WI156', rate: 0.5, description: 'Payments made by credit card companies - Individual' },
    { atc: 'WI159', rate: 15, description: 'Additional payments to government personnel from importers, shipping and airline companies or their agents for overtime services' },
    { atc: 'WI640', rate: 1, description: 'Income payments made by the government to its local/resident suppliers of goods - Individual' },
    { atc: 'WI157', rate: 2, description: 'Income payments made by the government to its local/resident suppliers of service - Individual' },
    { atc: 'WI158', rate: 1, description: 'Income payment made by top withholding agents to their local/resident supplier of goods other than those covered by other rates of withholding tax - Individual' },
    { atc: 'WI160', rate: 2, description: 'Income payment made by top withholding agents to their local/resident supplier of services other than those covered by other rates of withholding tax - Individual' },
    { atc: 'WI515', rate: 5, description: 'Commission, rebates, discounts & other similar considerations pd/granted to indepndnt & exclusive sales reps & mkting agents & sub-agents of multi-level marketing co. inc. multilevel mrkting co.- If gross income for the current yr did not exceed P3M' },
    { atc: 'WI516', rate: 10, description: 'Commission, rebates, discounts & other similar considerations pd/granted to indepndnt & exclusive sales reps & mkting agents & sub-agents of multi-level mktng co. inc. multilevel mrkting co.-if gross income > P3M or VAT Registered regardless of amt' },
    { atc: 'WI530', rate: 1, description: 'Gross payments to embalmers by funeral parlors' },
    { atc: 'WI535', rate: 1, description: 'Payments made by pre-need companies to funeral parlors - Individual' },
    { atc: 'WI540', rate: 5, description: 'Tolling fee paid to refineries - Individual' },
    { atc: 'WI610', rate: 1, description: 'Income payments made to suppliers of Agricultural products - Individual' },
    { atc: 'WI630', rate: 5, description: 'Income payments on purchases of minerals, mineral products & quarry resources - Individual' },
    { atc: 'WI632', rate: 1, description: 'Income payments on purchases of gold by Bangko Sentral ng Pilipinas (BSP) from gold miners/suppliers under PD 1899, as amended by R.A. No. 7076- Individual' },
    { atc: 'WI650', rate: 15, description: 'On gross amount of refund given by Meralco to customers with active contracts as classified by Meralco - Individual' },
    { atc: 'WI651', rate: 15, description: 'On gross amount of refund given by Meralco to customers with terminated contracts as classified by Meralco - Individual' },
    { atc: 'WI660', rate: 10, description: "WITHHOLDING ON GROSS AMOUNT OF INTEREST ON THE REFUND OF METER DEPOSIT WHETHER PAID DIRECTLY TO THE CUSTOMERS OR APPLIED AGAINST CUSTOMER'S BILLING - RESIDENTIAL AND GENERAL SERVICE CUSTOMERS WHOSE MONTHLY ELECTRICITY CONSUMPTION EXCEEDS 200 KWH AS C" },
    { atc: 'WI661', rate: 15, description: "WITHHOLDING ON GROSS AMOUNT OF INTERST ONT HE REFIND OF METER DEPOSIT WHETER PAID DIRECTLY TO THE CUSTOMERS OR APPLIED AGAINST CUSTOMER'S BILLING - RESIDENTIAL AND GENERA; SERVICE CUSTOMERS WHOSE MONTLY ELECTRICITY CONSUMPTION EXCEEDS200 KWH AS CLASS" },
    { atc: 'WI662', rate: 10, description: "WITHHOLDING ON GROSS AMOUNT OF INTERESTO N THE REFUND OF METER DEPOSIT WHETHEER PAID DIRECTLY TO THE CUSTOMERS OR APPLIED AGAINST CUSTOMER'S BILLING - RESIDENTIAL AND GENERAL SERVICE CUSTOMERS WHOSE MONTLY ELECTRICITY CONSUMPTION EXCEEDS 200 KWH AS CL" },
    { atc: 'WI663', rate: 15, description: "WITHHOLDING ON GROSS AMOUNT OF INTEREST ON THE REFUND OF METER DEPOSIT WHETHER PAID DIRECTLY TO THE CUSTOMERS OR APPLIED CUSTOMER'S BILLING - NON - RESIDENTIAL CUSTOMERS WHOSE MONTLY ELECTRICITY CONSUMPTION EXCEEDS 200 KWH AS CLASSIFIED BY OTH" },
    { atc: 'WI680', rate: 5, description: 'INCOME PAYMENTS MADE BY POLITICAL PARTIES AND CANDIDATES OF LOCAL AND NATIONAL ELECTIONS OF ALL THEIR CAMPAIGN EXPENDITURES, AND INCOME PAYMENTS MADE BY INDIVIDUALS OR JURIDICAL PERSONS FOR THEIR PURCHASES OF GOODS AND SERVICES INTENDED TO BE GIVEN A' },
    { atc: 'WI710', rate: 15, description: 'INTEREST INCOME DERIVED FROM ANY OTHER DEBT INSTRUMENTS NOT WITHIN THE COVERAGE OF DEPOSIT SUBSTITUTES' },
    { atc: 'WI720', rate: 1, description: 'Income payments on locally produced raw sugar - Individual' },
    { atc: 'WI770', rate: 1, description: 'Income payments made by joint ventures, whether incorporated or not, taxable or non-taxable, to their local/resident supplier of goods' },
    { atc: 'WI780', rate: 2, description: 'Income payments made by joint ventures, whether incorporated or not, taxable or non-taxable, to their local/resident supplier of services' },
    { atc: 'WI820', rate: 0.5, description: 'On the gross remittances by e-marketplace operators to the sellers/merchants for the goods or services sold/paid through their platform/facility' },
    { atc: 'WI830', rate: 0.5, description: 'On the gross remittances by digital financial services providers to the sellers/merchants for the goods or services sold/paid through their platform/facility' },
    { atc: 'WC010', rate: 10, description: 'Professionals/ talent fees paid to juridical persons - If the current year’s gross income is P720,000 and below' },
    { atc: 'WC011', rate: 15, description: 'Professionals/ talent fees paid to juridical persons - If the current year’s gross income exceeds P 720,000' },
    { atc: 'WC020', rate: 10, description: 'Professional entertainers such as, but not limited to actors and actresses, singers, lyricists, composers, emcees - If gross income for the current year did not exceed P 720,000' },
    { atc: 'WC021', rate: 15, description: 'Professional entertainers such as, but not limited to actors and actresses, singers, lyricists, composers, emcees - - If gross income exceeds P 720,000' },
    { atc: 'WC030', rate: 10, description: 'Professional athletes including basketball players, pelotaris and jockeys - If gross income for the current year did not exceed P 720,000' },
    { atc: 'WC031', rate: 15, description: 'Professional athletes including basketball players, pelotaris and jockeys -  - If gross income exceeds P 720,000' },
    { atc: 'WC040', rate: 10, description: 'All directors and producers involved in movies, stage, radio, television and musical productions - If gross income for the current year did not exceed P 720,000' },
    { atc: 'WC041', rate: 15, description: 'All directors and producers involved in movies, stage, radio, television and musical productions - If gross income exceeds P 720,000' },
    { atc: 'WC050', rate: 10, description: 'Management and technical consultants paid to juridical person - If the current year’s gross income is P 720,000 and below' },
    { atc: 'WC051', rate: 15, description: 'Management and technical consultants paid to juridical person - If the currents year’s gross income exceeds P720,000' },
    { atc: 'WC060', rate: 10, description: 'Business and bookkeeping agents and agencies - If gross income for the current year did not exceed P 720,000' },
    { atc: 'WC061', rate: 15, description: 'Business and bookkeeping agents and agencies - If gross income exceeds P 720,000' },
    { atc: 'WC070', rate: 10, description: 'Insurance agents and insurance adjusters - If gross income for the current year did not exceed P 720,000' },
    { atc: 'WC071', rate: 15, description: 'Insurance agents and insurance adjusters - If gross income exceeds P 720,000' },
    { atc: 'WC080', rate: 10, description: 'Other recipients of talent fees - If gross income for the current year did not exceed P 720,000' },
    { atc: 'WC081', rate: 15, description: 'Other recipients of talent fees - If gross income exceeds P 720,000' },
    { atc: 'WC100', rate: 5, description: 'Rentals- real/personal properties, poles, satellites & transmission facilities, billiboards - Corporate' },
    { atc: 'WC110', rate: 5, description: 'Cinematographic film rentals - Corporate' },
    { atc: 'WC120', rate: 2, description: 'Income payments to prime contractors/sub-contractors - Corporate' },
    { atc: 'WC139', rate: 10, description: 'Gross commission or service fees of custom, insurance, stock, real estate, immigration and commercial brokers & fees of agents of professional entertainers - if gross income did not exceed 720,000- Corporate' },
    { atc: 'WC140', rate: 15, description: 'Gross commission or service fees of custom, insurance, stock, real estate, immigration and commercial brokers & fees of agents of professional entertainers - if gross income exceeds 720,000- Corporate' },
    { atc: 'WC151', rate: 10, description: 'Professional fees paid to medical practitioners (inc.doctors of medicine doctors of veterinary sciences & dentists) by hospitals & clinics or paid directly by Health Maintenance Org (HMOs) &/or similar est - If gross income for the current yr < P720K' },
    { atc: 'WC150', rate: 15, description: 'Professional fees paid to medical practitioners (inc.doctors of medicine doctors of veterinary sciences & dentists) by hospitals & clinics or paid directly by Health Maintenance Org (HMOs) &/or similar est - If gross income exceeds P720K' },
    { atc: 'WC156', rate: 0.5, description: 'Payments made by credit card companies - Corporate' },
    { atc: 'WC640', rate: 1, description: 'Income payments made by the government to its local/resident suppliers of goods - Corporate' },
    { atc: 'WC157', rate: 2, description: 'Income payments made by the government to its local/resident suppliers of services - Corporate' },
    { atc: 'WC158', rate: 1, description: 'Income payment made by top withholding agents to their local/resident supplier of goods other than those covered by other rates of withholding tax - Corporate' },
    { atc: 'WC160', rate: 2, description: 'Income payment made by top withholding agents to their local/resident supplier of services other than those covered by other rates of withholding tax - Corporate' },
    { atc: 'WC535', rate: 1, description: 'Payments made by pre-need companies to funeral parlors - Corporate' },
    { atc: 'WC540', rate: 5, description: 'Tolling fee paid to refineries - Corporate' },
    { atc: 'WC610', rate: 1, description: 'Income payments made to suppliers of Agricultural products - Corporate' },
    { atc: 'WC630', rate: 5, description: 'Income payments on purchases of minerals, mineral products & quarry resources - Corporate' },
    { atc: 'WC632', rate: 1, description: 'Income payments on purchases of gold by Bangko Sentral ng Pilipinas (BSP) from gold miners/suppliers under PD 1899, as amended by R.A. No. 7076- Corporate' },
    { atc: 'WC650', rate: 15, description: 'On gross amount of refund given by Meralco to customers with active contracts as classified by Meralco - Corporate' },
    { atc: 'WC651', rate: 15, description: 'On gross amount of refund given by Meralco to customers with terminated contracts as classified by Meralco - Corporate' },
    { atc: 'WC660', rate: 10, description: "WITHHOLDING ON GROSS AMOUNT OF INTEREST ON THE REFUND OF METER DEPOSIT WHETHER PAID DIRECTLY TO THE CUSTOMERS OR APPLIED AGAINST CUSTOMER'S BILLING - RESIDENTIAL AND GENERAL SERVICE CUSTOMERS WHOSE MONTHLY ELECTRICITY CONSUMPTION EXCEEDS 200 KWH AS C" },
    { atc: 'WC661', rate: 15, description: "WITHHOLDING ON GROSS AMOUNT OF INTEREST ON THE REFUND OF METER DEPOSIT WHETHER PAID DIRECTLY TO THE CUSTOMERS OR APPLIED AGAINST CUSTOMER'S BILLING - NON - RESIDENTIAL CUSTOMERS WHOSE MONTLY ELECTRICITY CONSUMPTION EXCEEDS 200 KWH AS CLASSIFIED BY ME" },
    { atc: 'WC662', rate: 10, description: "WITHHOLDING ON GROSS AMOUNT OF INTEREST ON THE REFUND OF METER DEPOSIT WHETHEER PAID DIRECTLY TO THE CUSTOMERS OR APPLIED AGAINST CUSTOMER'S BILLING - RESIDENTIAL AND GENERAL SERVICE CUSTOMERS WHOSE MONTLY ELECTRICITY CONSUMPTION EXCEEDS 200 KWH AS C" },
    { atc: 'WC663', rate: 15, description: "WITHHOLDING ON GROSS AMOUNT OF INTEREST ON THE REFUND OF METER DEPOSIT WHETHER PAID DIRECTLY TO THE CUSTOMERS OR APPLIED CUSTOMER'S BILLING - NON - RESIDENTIAL CUSTOMERS WHOSE MONTLY ELECTRICITY CONSUMPTION EXCEEDS 200 KWH AS CLASSIFIED BY OTHER ELEC" },
    { atc: 'WC680', rate: 5, description: 'INCOME PAYMENTS MADE BY POLITICAL PARTIES AND CANDIDATES OF LOCAL AND NATIONAL ELECTIONS OF ALL THEIR CAMPAIGN EXPENDITURES, AND INCOME PAYMENTS MADE BY INDIVIDUALS OR JURIDICAL PERSONS FOR THEIR PURCHASES OF GOODS AND SERVICES INTENDED TO BE GIVEN A' },
    { atc: 'WC690', rate: 1, description: 'Income payments received by Real Estate Investment Trust (REIT)' },
    { atc: 'WC710', rate: 15, description: 'INTEREST INCOME DERIVED FROM ANY OTHER DEBT INSTRUMENTS NOT WITHIN THE COVERAGE OF DEPOSIT SUBSTITUTES' },
    { atc: 'WC720', rate: 1, description: 'Income payments on locally produced raw sugar - Corporation' },
    { atc: 'WC770', rate: 1, description: 'Income payments made by joint ventures, whether incorporated or not, taxable or non-taxable, to their local/resident supplier of goods' },
    { atc: 'WC780', rate: 2, description: 'Income payments made by joint ventures, whether incorporated or not, taxable or non-taxable, to their local/resident supplier of services' },
    { atc: 'WC790', rate: 15, description: 'On the share of each co-venturer/member from the net income of the joint venture/consortium not taxable as corporation prior to actual or constructive distribution thereof' },
    { atc: 'WC820', rate: 0.5, description: 'On the gross remittances by e-marketplace operators to the sellers/merchants for the goods or services sold/paid through their platform/facility' },
    { atc: 'WC830', rate: 0.5, description: 'On the gross remittances by digital financial services providers to the sellers/merchants for the goods or services sold/paid through their platform/facility' },
];

export const atcExempt: AtcScheduleItem[] = [
    { atc: 'MC040', rate: 0, description: 'INCOME FROM FORFEITED PROPERTIES' },
    { atc: 'MC030', rate: 0, description: 'COMP. PYMTS ON DELQNT. ACCOUNTS & DISP. ASSESSMENTS' },
    { atc: 'MC021', rate: 0, description: 'CORPORATE TAXPAYERS' },
    { atc: 'MC020', rate: 0, description: 'TAX AMNESTY ON INCOME (CORPORATE)' },
    { atc: 'MC011', rate: 0, description: 'INDIVIDUAL TAXPAYERS' },
    { atc: 'MC010', rate: 0, description: 'TAX AMNESTY ON INCOME (INDIVIDUAL)' },
    { atc: 'II420', rate: 0, description: 'CGT ON SALE OF REAL PROPERTY (CAPITAL ASSETS) FOR INDIV' },
    { atc: 'II130', rate: 0, description: 'PARTNERS DISTRIB SHARE OF NET INC OF GEN PARTNERSHIP' },
    { atc: 'II120', rate: 0, description: 'PRIZES AMOUNTING TO: 10,000 OR LESS' },
    { atc: 'II110', rate: 0, description: 'INTEREST - (INDIVIDUAL PAYEES)' },
    { atc: 'II090', rate: 0, description: 'TRANSPO CONTR (INDIVIDUAL)  CARRIAGE OF GOODS AND MERCHDSE BELOW 2,000' },
    { atc: 'II080', rate: 0, description: 'OTHERS (SPECIFY) - (INDIVIDUAL PAYEES)' },
    { atc: 'II070', rate: 0, description: 'PENSIONS' },
    { atc: 'II060', rate: 0, description: 'PREMIUM AND ANNUITY - (INDIVIDUAL PAYEES)' },
    { atc: 'II051', rate: 0, description: 'RENT - PERSONAL PROPERTY REGARDLESS OF  AMOUNT (INDIVIDUAL)' },
    { atc: 'II050', rate: 0, description: 'RENT FOR REAL PROPERTY BELOW P500 MONTH (USED IN BUSINESS)' },
    { atc: 'II020', rate: 0, description: 'NRC INCOME' },
    { atc: 'II013', rate: 0, description: 'ESTATES AND TRUST -MIXED INCOME' },
    { atc: 'II012', rate: 0, description: 'RESIDENT ALIEN - PURE BUSINESS' },
    { atc: 'II011', rate: 0, description: 'PURE COMPENSATION INCOME -CITIZENS' },
    { atc: 'II010', rate: 0, description: 'INCOME FROM COMP. ANDBUS./PROF' },
    { atc: 'IC370', rate: 0, description: 'ON IMPROPERLY ACCUMULATED EARNINGS TAX' },
    { atc: 'IC191', rate: 0, description: 'FOREIGN CURRENCY DEPOSIT UNITS (FCDUS)' },
    { atc: 'IC190', rate: 0, description: 'OFFSHORE BANKING UNITS (OBUS)' },
    { atc: 'IC170', rate: 0, description: 'INTEREST - (CORPORATE PAYEES)' },
    { atc: 'IC160', rate: 0, description: 'TRANSPO CONTR (CORPORATE) CARRIAGE OF GOODS AND MERCHDSE BELOW P2000' },
    { atc: 'IC150', rate: 0, description: 'OTHERS (SPECIFY) - (CORPORATE PAYEES)' },
    { atc: 'IC140', rate: 0, description: 'PREMIUM AND ANNUITY - (CORPORATE PAYEES)' },
    { atc: 'IC130', rate: 0, description: 'RENT - PERSONAL PROPERTY REGARDLESS OF AMOUNT (CORPORATE)' },
    { atc: 'IC120', rate: 0, description: 'PRIZES REGARDLESS OF AMOUNT' },
    { atc: 'IC101', rate: 0, description: 'REGIONAL OPERATING HEADQUARTERS OF MULTINATIONAL COMP' },
    { atc: 'IC100', rate: 0, description: 'FOREIGN OBU/FCDU' },
    { atc: 'IC090', rate: 0, description: 'FOREIGN MUTUAL LIFE INSURANCE CO.' },
    { atc: 'IC080', rate: 0, description: 'RFC -INTERNATIONAL CARRIERS' },
    { atc: 'IC070', rate: 0, description: 'ORDINARY RESIDENT FOREIGN CORP.' },
    { atc: 'IC060', rate: 0, description: 'INCOME TAX -FCDU' },
    { atc: 'IC055', rate: 0, description: 'MINIMUM CORPORATE INCOME TAX' },
    { atc: 'IC050', rate: 0, description: 'INCOME TAX - MUTUAL LIFE INSURANCE COMPANIES' },
    { atc: 'IC041', rate: 0, description: 'NATL & LOC GOVT UNITS (FOR PROPRIETARY ACTVTIES) EXCEPT PUBS' },
    { atc: 'IC040', rate: 0, description: 'GOVT OWNED OR CONTROLLED CORP' },
    { atc: 'IC031', rate: 0, description: 'NON STOCK, NON PROFIT HOSPITALS' },
    { atc: 'IC030', rate: 0, description: 'PRIVATE EDUC INST, STOCK OR NON STOCK' },
    { atc: 'IC021', rate: 0, description: 'PROFNL FEES PAID TO GEN PROF PARTNRSHIPS (EXCEPT TO PARTNRSHP OF MED)' },
    { atc: 'IC020', rate: 0, description: 'PARTNERSHIP IN TRADE INCOME TAX' },
    { atc: 'IC011', rate: 0, description: 'NON-STOCK NON-PROFIT ORGANIZATION' },
    { atc: 'IC010', rate: 0, description: 'INCOME TAX- ORDINARY DOMESTIC CORP.' },
    { atc: 'FP010', rate: 0, description: 'FINES & PEN.- ON TAX ON INCOME' },
    { atc: 'EI900', rate: 0, description: 'EXCESS INCOME TAX' },
    { atc: 'DI900', rate: 0, description: 'DEFAULT INCOME TAX' },
];

export const atcWG: AtcScheduleItem[] = [
    { atc: 'WV010', rate: 5, description: 'FWVAT on payments for purchases of Goods' },
    { atc: 'WV020', rate: 5, description: 'FWVAT on payments for purchases of Services' },
    { atc: 'WV040', rate: 12, description: 'Lease or use of properties or property rights owned by non-residents (Government Withholding Agent)' },
    { atc: 'WV050', rate: 12, description: 'Lease or use of properties or property rights owned by non-residents (Private Withholding Agent)' },
    { atc: 'WV060', rate: 12, description: 'Other services rendered in the Philippines by non-residents (Government Withholding Agent)' },
    { atc: 'WV070', rate: 12, description: 'Other services rendered in the Philippines by non-residents (Private Withholding Agent)' },
    { atc: 'WB030', rate: 3, description: 'Tax on carriers and keepers of garages' },
    { atc: 'WB040', rate: 2, description: 'Franchise Tax on Gas and Water Utilities' },
    { atc: 'WB050', rate: 3, description: 'Franchise Tax on radio & TV broadcasting companies whose annual gross receipts does not exceed P10M & who are not VAT registered taxpayers' },
    { atc: 'WB070', rate: 2, description: 'Tax on life insurance premiums' },
    { atc: 'WB080', rate: 3, description: 'Persons exempt from VAT under Sec. 109(v) (creditable)-Government Withholding Agent' },
    { atc: 'WB090', rate: 10, description: 'Tax on overseas dispatch, message or conversation originating from the Philippines' },
    { atc: 'WB301', rate: 5, description: 'Tax on Banks and Non-Bank Financial Internediaries Performing Quasi-Banking Functions. On interest, commissions and discounts from lending activities as well as income from financial leasing, on the basis of remaining maturities of instruments fr' },
    { atc: 'WB303', rate: 1, description: 'Tax on Banks and Non-Bank Financial Intermediaries Performing Quasi-Banking Functions. On interest, commissions and discounts from lending activities as well as income from financial leasing, on the basis of remaining maturities of instruments f' },
    { atc: 'WB102', rate: 0, description: 'Tax on Banks and Non-Bank Financial Intermediaries Performing Quasi-Banking Functions. On dividends and equity shares and net income of subsidiaries' },
    { atc: 'WB103', rate: 7, description: 'Tax on Banks and Non-Bank Financial Intermediaries Performing Quasi-Banking Functions. On royalties, rentals of property, real or personal, profits from exchange and all other items treated as gross income under the Code' },
    { atc: 'WB104', rate: 7, description: 'Tax on Banks and Non-Bank Financial Intermediaries Perfoming Quasi-Banking Functions. On the net trading gains within the taxable year on foreign currency, debt securities, derivatives, and other similar financial instruments' },
    { atc: 'WB108', rate: 5, description: 'Tax on Other Non-Banks Financial Intermediaries Not Performing Quasi-Banking Functions. On interest, commissions and discounts from lending activities as well as income from financial leasing, on the basis of the remaining maturities of instrument f' },
    { atc: 'WB109', rate: 1, description: 'Tax on Other Non-Banks Financial Intermediaries Not Performing Quasi-Banking Functions. On interest, commissions and discounts from lending activities as well as income from financial leasing, on the basis of the remaining maturities of instrument f' },
    { atc: 'WB110', rate: 5, description: 'Tax on Other Non-Banks Financial Intermediaries Not Performing Quasi-Banking Functions. On all other items treated as gross income under the Code' },
    { atc: 'WB120', rate: 4, description: 'Business Tax on Agents of foreign insurance co. - insurance agents' },
    { atc: 'WB121', rate: 5, description: 'Business Tax on Agents of foreign insurance co. - owner of the property' },
    { atc: 'WB130', rate: 3, description: 'Tax on International Carriers' },
    { atc: 'WB140', rate: 18, description: 'Tax on cockpits' },
    { atc: 'WB150', rate: 18, description: 'Tax on cabarets, night and day clubs' },
    { atc: 'WB160', rate: 10, description: 'Tax on boxing exhibitions' },
    { atc: 'WB170', rate: 15, description: 'Tax on professional basketball games' },
    { atc: 'WB180', rate: 30, description: 'Tax on jai-alai & race tracks' },
    { atc: 'WB200', rate: 0.6, description: 'Tax on sale, barter or exchange of shares of stocks listed and traded through the Local Stock Exchange' },
    { atc: 'WB201', rate: 4, description: 'Tax on shares of stock sold or exchanged through initial and secondary public offering - Not over 25%' },
    { atc: 'WB202', rate: 2, description: 'Tax on shares of stock sold or exchanged through initial and secondary public offering - Over 25% but not exceeding 33 1/3%' },
    { atc: 'WB203', rate: 1, description: 'Tax on shares of stock sold or exchanged through initial and secondary public offering - Over 33 1/3%' },
    { atc: 'WV012', rate: 12, description: 'VAT Withholding on Purchase of Goods (with waiver of privilege to claim input tax credit (creditable)' },
    { atc: 'WV014', rate: 12, description: 'Vat Withholding on Purchase of Goods (with waiver of privilege to claim input tax credit (final)' },
    { atc: 'WV022', rate: 12, description: 'VAT Withholding on Purchase of Services (with waiver of privilege to claim input tax credit (creditable)' },
    { atc: 'WV024', rate: 12, description: 'VAT Withholding on Purchase of Services (with waiver of privilege to claim input tax credit (final)' },
    { atc: 'WB082', rate: 3, description: 'Persons exempt from VAT under Section 109v (creditable) - Private Withholding Agent' },
    { atc: 'WB084', rate: 3, description: 'Persons exempt from VAT under Section 109v (final)' },
    { atc: 'PT320', rate: 5, description: 'Gaming Tax' },
];

export const atcWF: AtcScheduleItem[] = [
    { atc: 'WC180', rate: 20, description: 'Interest on foreign loans payable to non-resident foreign corporations (NRFCs)' },
    { atc: 'WC190', rate: 10, description: 'Interest and other income payments on foreign currency transactions/loans payable to OBUs' },
    { atc: 'WC191', rate: 10, description: 'Interest and other income payments on foreign currency transactions/loans payable to FCDUs' },
    { atc: 'WI202', rate: 10, description: 'Cash dividend payments by domestic corporation to citizens and resident aliens' },
    { atc: 'WI203', rate: 10, description: 'Property dividend payments by domestic corporation to citizens and resident aliens' },
    { atc: 'WC212', rate: 25, description: 'Cash dividend payment by domestic corporation to Non-Resident Foreign Corporations' },
    { atc: 'WC213', rate: 25, description: 'Property dividend payment by domestic corporation to Non-Resident Foreign Corporations' },
    { atc: 'WC222', rate: 15, description: 'Cash dividend payment by domestic corporation to Non-Resident Foreign Corporations whose countries allowed tax deemed paid credit (subject to tax sparing rule)' },
    { atc: 'WC223', rate: 15, description: 'Property dividend payment by domestic corporation to Non-Resident Foreign Corporations whose countries allowed tax deemed paid credit (subject to tax sparing rule)' },
    { atc: 'WI224', rate: 20, description: 'Cash dividend payment by domestic corporation to non-resident alien engaged in trade or business (NRAETB)' },
    { atc: 'WI225', rate: 20, description: 'Property  dividend payment by domestic corporation to non-resident alien engaged in trade or business (NRAETB)' },
    { atc: 'WI226', rate: 20, description: 'Share of a NRAETB in the distributable net income after tax of a partnership (except GPP) of which he is a partner, or share in the net income after tax of an association,  joint account, or a joint venture taxable as a corporation of which he is a m' },
    { atc: 'WC230', rate: 25, description: 'On other payments to non-resident foreign  corporations (NRFCs)' },
    { atc: 'WI240', rate: 10, description: 'Distributive share of individual partners in a taxable partnerships, association,  joint account, or joint venture or consortium' },
    { atc: 'WI250', rate: 20, description: 'All kinds of royalty payments to citizens, resident aliens and non-resident aliens engaged in trade or business (other than WI 380 and WI 341)' },
    { atc: 'WC250', rate: 20, description: 'All kinds of royalty payments to domestic and resident foreign corporation' },
    { atc: 'WI260', rate: 20, description: 'On prizes exceeding P10,000 and other winnings paid to individuals' },
    { atc: 'WC280', rate: 15, description: 'Branch profit remittances by all  corporations except PEZA/SBMA/CDA registered' },
    { atc: 'WC290', rate: 4.5, description: 'On gross rentals, lease and charter fees derived by non-resident owner or lessor of foreign vessels' },
    { atc: 'WC300', rate: 7.5, description: 'On the gross rentals, lease and charter fees derived by non-resident lessor of aircraft, machineries and other equipment' },
    { atc: 'WI310', rate: 8, description: 'On payments to oil exploration service contractors and subcontractors (OESS) - Individual (NRAETB)' },
    { atc: 'WC310', rate: 8, description: 'On payments to oil exploration service contractors and subcontractors (OESS) - Corporate (non-resident foreign corporation engage in trade or business)' },
    { atc: 'WI320', rate: 0, description: 'Payments to Filipinos or alien individuals employed by Foreign Petroleum Service Contractors/Subcontractors, Offshore Banking Units and Regional or Area Headquarters and Regional Operating Headquarters of Multinational Companies occupying executive/m' },
    { atc: 'WI330', rate: 25, description: 'Payments to NRANETB except on sale of shares in domestic corporation and real property' },
    { atc: 'WI340', rate: 25, description: 'On payments to non-resident individual  cinematographic film  owners, lessors or distributors' },
    { atc: 'WC340', rate: 25, description: 'On payments to foreign corporate cinematographic film  owners, lessors or distributors' },
    { atc: 'WI341', rate: 25, description: 'Royalties paid to NRAETB on cinematographic films and similar works' },
    { atc: 'WI350', rate: 30, description: 'Final tax on interest or other  payments  upon tax-free covenant bonds, mortgages,  deeds of trust or other obligations under Sec. 57C of the NIRC of 1997' },
    { atc: 'WI380', rate: 10, description: 'Royalties paid to citizens, resident aliens and NRAETB on books, other literary works and musical composition' },
    { atc: 'WI410', rate: 10, description: 'Informer\'s cash reward paid to individuals' },
    { atc: 'WC410', rate: 10, description: 'Informer\'s cash reward paid to juridical persons' },
    { atc: 'WF330', rate: 25, description: 'Payment of fringe benefits to Non-Resident Alien Not Engaged in Trade or Business (NRAETB)' },
    { atc: 'WF360', rate: 35, description: 'Employees other than rank and file (Fringe Benefit Tax)  based on the grossed up monetary value' },
    { atc: 'WC700', rate: 10, description: 'Cash or property dividend paid by a Real Estate Investment Trust (REIT) - Corporate' },
    { atc: 'WI700', rate: 10, description: 'Cash or property dividend paid by a Real Estate Investment Trust (REIT) - Individual' },
    { atc: 'WI740', rate: 25, description: 'Final Withholding Tax on Foreign Nationals Employed by POGO Entities' },
    { atc: 'WI750', rate: 0, description: 'On gross income earned by foreign nationals or non-Filipino citizens, regardless of their residency, who are employed and assigned in the Philippines by Offshore Gaming Licensee or its Accredited Service Provider' },
];

